# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/projects')),
                ('published', models.CharField(max_length=30)),
                ('github_url', models.URLField(max_length=50)),
                ('project_url', models.URLField(max_length=50)),
                ('button_text', models.CharField(default='Visit Page', max_length=20)),
            ],
        ),
    ]
