# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160607_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateField(),
        ),
    ]
