# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160618_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
