# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160618_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default='', max_length=50),
        ),
    ]
